base_url = "https://alfazet.xyz"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

default_language = "en"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "alfazet"

header_nav = [
  { url = "/", name_en = "/home" },
  { url = "/about", name_en = "/about" },
]
